### ISSUE TITLE
Feature request. Automatically load previous logs.

### ISSUE THREAD

**Issue by 1337cookie** [the-hideout/TarkovMonitor#47]
If I run "Force Read Log Files" in chronological order it updates my untracked tasks. Would be cool if there was a button to do this OR we could just select all the logs to load simultaneously.

**Comment by squidninja17** [comment]
I second this. Sounds 100% doable and should be an essential feature.

**Comment by gaschenk** [comment]
While this is possible and I would have a rough draft, you will run into the issue that a lot of requests will timeout as TarkovMonitor hasn't been built with resiliency in mind regarding Tarkov Tracker and accessing its API.

**Comment by Razzmatazzz** [comment]
Yes, there is the rate limit issue with Tarkov Tracker's API. We would have to build in some metering to make sure we don't exceed the limit.

But there's also the issue of knowing how far back to read logs. Would need to know the start of the current wipe in order to avoid reading logs from last wipe. There's also the issue of reading logs from a different account if the user has more than one EFT account. I suppose one way to solve all that would be to let the user specify how far back to go with the logs.

**Comment by gaschenk** [comment]
> Would need to know the start of the current wipe in order to avoid reading logs from last wipe.

In that regard it would be an option to differentiate if it's a previous wipe, if the newest Version has a different minor version, at least that's as far as I'm aware when normally a wipe should have happened, so it would allow to read just every log, parse every log entry, sort by date, filter out any version entry that has a different minor version from the current version.

Furthermore in regard to logs and being able to find new information, you could attempt to change NLog.config and set everything to TRACE and well hope to see something new, potentially that is.

**Comment by Razzmatazzz** [comment]
It's an interesting idea to use the minor version number as a cutoff to read previous logs, wipes don't always perfectly coincide with a new minor version. 

As for editing the NLog.config, I believe that will cause the game to fail integrity checks.

**Comment by gaschenk** [comment]
> As for editing the NLog.config, I believe that will cause the game to fail integrity checks.

In fact it does.

As for well fixing certain stuff up, I'd recommend looking at Refit in order to implement a TarkovTracker API, which could potentially be it's own personal Library and with Libraries such as Polly you could easily add rate limiting.

**Comment by ar1a** [comment]
Is there an option of retrieving task data from tarkovtracker in bulk, checking for discrepancies between the local state that's been rebuilt (from the "force read all logs" button), and then only submitting changes for each task that's mismatched, instead of checking all 340 tasks one api call after the other
